package uz.etalon.crm.core.ui.regions

/**
 * The Uzbekistan region catalogue — 14 viloyats and 206 tumans, transcribed from
 * `src/lib/regions/data.ts` (itself generated from the kenjebaev `regions.json`). Both
 * spellings are carried because the web widget writes the CYRILLIC name into the address and
 * `parseAddress` matches on either, so a row written here must be recognisable to the web when
 * the same client is opened there.
 *
 * Canonical copy: this table lives in `:core:ui` (rather than `:feature:clients`, which only
 * consumes it) so `formatAddressLine` — used by orders and client screens across the app — can
 * convert a stored address's viloyat/tuman parts to Cyrillic for display without a second,
 * independently-drifting copy of the same 220 rows. `:feature:clients` re-exports these from
 * its own `Regions.kt` rather than declaring them again.
 *
 * Mahallas are deliberately absent, as on the web: the source has ~10 000 of them and they
 * are typed into the street field instead.
 */
data class Viloyat(val id: Int, val name: String, val nameUz: String)

data class Tuman(val id: Int, val viloyatId: Int, val name: String, val nameUz: String)

val VILOYATS: List<Viloyat> = listOf(
    Viloyat(1, "Qoraqalpog‘iston Respublikasi", "Қорақалпоғистон Республикаси"),
    Viloyat(2, "Andijon viloyati", "Андижон вилояти"),
    Viloyat(3, "Buxoro viloyati", "Бухоро вилояти"),
    Viloyat(4, "Jizzax viloyati", "Жиззах вилояти"),
    Viloyat(5, "Qashqadaryo viloyati", "Қашқадарё вилояти"),
    Viloyat(6, "Navoiy viloyati", "Навоий вилояти"),
    Viloyat(7, "Namangan viloyati", "Наманган вилояти"),
    Viloyat(8, "Samarqand viloyati", "Самарқанд вилояти"),
    Viloyat(9, "Surxondaryo viloyati", "Сурхондарё вилояти"),
    Viloyat(10, "Sirdaryo viloyati", "Сирдарё вилояти"),
    Viloyat(11, "Toshkent viloyati", "Тошкент вилояти"),
    Viloyat(12, "Farg‘ona viloyati", "Фарғона вилояти"),
    Viloyat(13, "Xorazm viloyati", "Хоразм вилояти"),
    Viloyat(14, "Toshkent shahri", "Тошкент шаҳри"),
)

val TUMANS: List<Tuman> = listOf(
    Tuman(15, 1, "Amudaryo tumani", "Амударё тумани"),
    Tuman(16, 1, "Beruniy tumani", "Беруний тумани"),
    Tuman(17, 1, "Kegeyli tumani", "Кегейли тумани"),
    Tuman(18, 1, "Qanliko‘l tumani", "Қанликўл тумани"),
    Tuman(19, 1, "Qorao‘zak tumani", "Қораўзак тумани"),
    Tuman(20, 1, "Qo‘ng‘irot tumani", "Қўнғирот тумани"),
    Tuman(21, 1, "Mo‘ynoq tumani", "Мўйноқ тумани"),
    Tuman(22, 1, "Nukus tumani", "Нукус тумани"),
    Tuman(23, 1, "Nukus shahri", "Нукус шаҳри"),
    Tuman(24, 1, "Taxtako‘pir tumani", "Тахтакўпир тумани"),
    Tuman(25, 1, "To‘rtko‘l tumani", "Тўрткўл тумани"),
    Tuman(26, 1, "Xo‘jayli tumani", "Хўжайли тумани"),
    Tuman(27, 1, "Chimboy tumani", "Чимбой тумани"),
    Tuman(28, 1, "Shumanay tumani", "Шуманай тумани"),
    Tuman(29, 1, "Ellikqal‘a tumani", "Элликқалъа тумани"),
    Tuman(30, 2, "Andijon shahri", "Андижон шаҳри"),
    Tuman(31, 2, "Andijon tumani", "Андижон тумани"),
    Tuman(32, 2, "Asaka tumani", "Асака тумани"),
    Tuman(33, 2, "Baliqchi tumani", "Балиқчи тумани"),
    Tuman(34, 2, "Buloqboshi tumani", "Булоқбоши тумани"),
    Tuman(35, 2, "Bo‘z tumani", "Бўз тумани"),
    Tuman(36, 2, "Jalaquduq tumani", "Жалақудуқ тумани"),
    Tuman(37, 2, "Izboskan tumani", "Избоскан тумани"),
    Tuman(38, 2, "Qorasuv shahri", "Қорасув шаҳри"),
    Tuman(39, 2, "Qo‘rg‘ontepa tumani", "Қўрғонтепа тумани"),
    Tuman(40, 2, "Marhamat tumani", "Марҳамат тумани"),
    Tuman(41, 2, "Oltinko‘l tumani", "Олтинкўл тумани"),
    Tuman(42, 2, "Paxtaobod tumani", "Пахтаобод тумани"),
    Tuman(43, 2, "Ulug‘nor tumani", "Улуғнор тумани"),
    Tuman(44, 2, "Xonabod tumani", "Хонабод тумани"),
    Tuman(45, 2, "Xo‘jaobod shahri", "Хўжаобод шаҳри"),
    Tuman(46, 2, "Shahrixon tumani", "Шаҳрихон тумани"),
    Tuman(47, 3, "Buxoro shahri", "Бухоро шаҳри"),
    Tuman(48, 3, "Buxoro tumani", "Бухоро тумани"),
    Tuman(49, 3, "Vobkent tumani", "Вобкент тумани"),
    Tuman(50, 3, "G‘ijduvon tumani", "Ғиждувон тумани"),
    Tuman(51, 3, "Jondor tumani", "Жондор тумани"),
    Tuman(52, 3, "Kogon tumani", "Когон тумани"),
    Tuman(53, 3, "Kogon shahri", "Когон шаҳри"),
    Tuman(54, 3, "Qorako‘l tumani", "Қоракўл тумани"),
    Tuman(55, 3, "Qorovulbozor tumani", "Қоровулбозор тумани"),
    Tuman(56, 3, "Olot tumani", "Олот тумани"),
    Tuman(57, 3, "Peshku tumani", "Пешку тумани"),
    Tuman(58, 3, "Romitan tumani", "Ромитан тумани"),
    Tuman(59, 3, "Shofirkon tumani", "Шофиркон тумани"),
    Tuman(60, 4, "Arnasoy tumani", "Арнасой тумани"),
    Tuman(61, 4, "Baxmal tumani", "Бахмал тумани"),
    Tuman(62, 4, "G‘allaorol tumani", "Ғаллаорол тумани"),
    Tuman(63, 4, "Do‘stlik tumani", "Дўстлик тумани"),
    Tuman(64, 4, "Sharof Rashidov tumani", "Шароф Рашидов тумани"),
    Tuman(65, 4, "Jizzax shahri", "Жиззах шаҳри"),
    Tuman(66, 4, "Zarbdor tumani", "Зарбдор тумани"),
    Tuman(67, 4, "Zafarobod tumani", "Зафаробод тумани"),
    Tuman(68, 4, "Zomin tumani", "Зомин тумани"),
    Tuman(69, 4, "Mirzacho‘l tumani", "Мирзачўл тумани"),
    Tuman(70, 4, "Paxtakor tumani", "Пахтакор тумани"),
    Tuman(71, 4, "Forish tumani", "Фориш тумани"),
    Tuman(72, 4, "Yangiobod tumani", "Янгиобод тумани"),
    Tuman(73, 5, "G‘uzor tumani", "Ғузор тумани"),
    Tuman(74, 5, "Dehqonobod tumani", "Деҳқонобод тумани"),
    Tuman(75, 5, "Qamashi tumani", "Қамаши тумани"),
    Tuman(76, 5, "Qarshi tumani", "Қарши тумани"),
    Tuman(77, 5, "Qarshi shahri", "Қарши шаҳри"),
    Tuman(78, 5, "Kasbi tumani", "Касби тумани"),
    Tuman(79, 5, "Kitob tumani", "Китоб тумани"),
    Tuman(80, 5, "Koson tumani", "Косон тумани"),
    Tuman(81, 5, "Mirishkor tumani", "Миришкор тумани"),
    Tuman(82, 5, "Muborak tumani", "Муборак тумани"),
    Tuman(83, 5, "Nishon tumani", "Нишон тумани"),
    Tuman(84, 5, "Chiroqchi tumani", "Чироқчи тумани"),
    Tuman(85, 5, "Shahrisabz tumani", "Шаҳрисабз тумани"),
    Tuman(86, 5, "Yakkabog‘ tumani", "Яккабоғ тумани"),
    Tuman(87, 6, "Zarafshon shahri", "Зарафшон шаҳри"),
    Tuman(88, 6, "Karmana tumani", "Кармана тумани"),
    Tuman(89, 6, "Qiziltepa tumani", "Қизилтепа тумани"),
    Tuman(90, 6, "Konimex tumani", "Конимех тумани"),
    Tuman(91, 6, "Navbahor tumani", "Навбаҳор тумани"),
    Tuman(92, 6, "Navoiy shahri", "Навоий шаҳри"),
    Tuman(93, 6, "Nurota tumani", "Нурота тумани"),
    Tuman(94, 6, "Tomdi tumani", "Томди тумани"),
    Tuman(95, 6, "Uchquduq tumani", "Учқудуқ тумани"),
    Tuman(96, 6, "Xatirchi tumani", "Хатирчи тумани"),
    Tuman(97, 7, "Kosonsoy tumani", "Косонсой тумани"),
    Tuman(98, 7, "Mingbuloq tumani", "Мингбулоқ тумани"),
    Tuman(99, 7, "Namangan tumani", "Наманган тумани"),
    Tuman(100, 7, "Namangan shahri", "Наманган шаҳри"),
    Tuman(101, 7, "Norin tumani", "Норин тумани"),
    Tuman(102, 7, "Pop tumani", "Поп тумани"),
    Tuman(103, 7, "To‘raqo‘rg‘on tumani", "Тўрақўрғон тумани"),
    Tuman(104, 7, "Uychi tumani", "Уйчи тумани"),
    Tuman(105, 7, "Uchqo‘rg‘on tumani", "Учқўрғон тумани"),
    Tuman(106, 7, "Chortoq tumani", "Чортоқ тумани"),
    Tuman(107, 7, "Chust tumani", "Чуст тумани"),
    Tuman(108, 7, "Yangiqo‘rg‘on tumani", "Янгиқўрғон тумани"),
    Tuman(109, 8, "Bulung‘ur tumani", "Булунғур тумани"),
    Tuman(110, 8, "Jomboy tumani", "Жомбой тумани"),
    Tuman(111, 8, "Ishtixon tumani", "Иштихон тумани"),
    Tuman(112, 8, "Kattaqo‘rg‘on tumani", "Каттақўрғон тумани"),
    Tuman(113, 8, "Kattaqo‘rg‘on shahri", "Каттақўрғон шаҳри"),
    Tuman(114, 8, "Qo‘shrabot tumani", "Қўшработ тумани"),
    Tuman(115, 8, "Narpay tumani", "Нарпай тумани"),
    Tuman(116, 8, "Nurobod tumani", "Нуробод тумани"),
    Tuman(117, 8, "Oqdaryo tumani", "Оқдарё тумани"),
    Tuman(118, 8, "Payariq tumani", "Паяриқ тумани"),
    Tuman(119, 8, "Pastdarg‘om tumani", "Пастдарғом тумани"),
    Tuman(120, 8, "Paxtachi tumani", "Пахтачи тумани"),
    Tuman(121, 8, "Samarqand tumani", "Самарқанд тумани"),
    Tuman(122, 8, "Samarqand shahri", "Самарқанд шаҳри"),
    Tuman(123, 8, "Toyloq tumani", "Тойлоқ тумани"),
    Tuman(124, 8, "Urgut tumani", "Ургут тумани"),
    Tuman(125, 9, "Angor tumani", "Ангор тумани"),
    Tuman(126, 9, "Boysun tumani", "Бойсун тумани"),
    Tuman(127, 9, "Denov tumani", "Денов тумани"),
    Tuman(128, 9, "Jarqo‘rg‘on tumani", "Жарқўрғон тумани"),
    Tuman(129, 9, "Qiziriq tumani", "Қизириқ тумани"),
    Tuman(130, 9, "Qumqo‘rg‘on tumani", "Қумқўрғон тумани"),
    Tuman(131, 9, "Muzrabot tumani", "Музработ тумани"),
    Tuman(132, 9, "Oltinsoy tumani", "Олтинсой тумани"),
    Tuman(133, 9, "Sariosiyo tumani", "Сариосиё тумани"),
    Tuman(134, 9, "Termiz tumani", "Термиз тумани"),
    Tuman(135, 9, "Termiz shahri", "Термиз шаҳри"),
    Tuman(136, 9, "Uzun tumani", "Узун тумани"),
    Tuman(137, 9, "Sherobod tumani", "Шеробод тумани"),
    Tuman(138, 9, "Sho‘rchi tumani", "Шўрчи тумани"),
    Tuman(139, 10, "Boyovut tumani", "Боёвут тумани"),
    Tuman(140, 10, "Guliston tumani", "Гулистон тумани"),
    Tuman(141, 10, "Guliston shahri", "Гулистон шаҳри"),
    Tuman(142, 10, "Mirzaobod tumani", "Мирзаобод тумани"),
    Tuman(143, 10, "Oqoltin tumani", "Оқолтин тумани"),
    Tuman(144, 10, "Sayxunobod tumani", "Сайхунобод тумани"),
    Tuman(145, 10, "Sardoba tumani", "Сардоба тумани"),
    Tuman(146, 10, "Sirdaryo tumani", "Сирдарё тумани"),
    Tuman(147, 10, "Xovos tumani", "Ховос тумани"),
    Tuman(148, 10, "Shirin shahri", "Ширин шаҳри"),
    Tuman(149, 10, "Yangier shahri", "Янгиер шаҳри"),
    Tuman(150, 11, "Angren shahri", "Ангрен шаҳри"),
    Tuman(151, 11, "Bekobod tumani", "Бекобод тумани"),
    Tuman(152, 11, "Bekobod shahri", "Бекобод шаҳри"),
    Tuman(153, 11, "Bo‘ka tumani", "Бўка тумани"),
    Tuman(154, 11, "Bo‘stonliq tumani", "Бўстонлиқ тумани"),
    Tuman(155, 11, "Zangiota tumani", "Зангиота тумани"),
    Tuman(156, 11, "Qibray tumani", "Қибрай тумани"),
    Tuman(157, 11, "Quyi Chirchiq tumani", "Қуйи Чирчиқ тумани"),
    Tuman(158, 11, "Oqqo‘rg‘on tumani", "Оққўрғон тумани"),
    Tuman(159, 11, "Olmaliq shahri", "Олмалиқ шаҳри"),
    Tuman(160, 11, "Ohangaron tumani", "Оҳангарон тумани"),
    Tuman(161, 11, "Parkent tumani", "Паркент тумани"),
    Tuman(162, 11, "Piskent tumani", "Пискент тумани"),
    Tuman(163, 11, "O‘rta Chirchiq tumani", "Ўрта Чирчиқ тумани"),
    Tuman(164, 11, "Chinoz tumani", "Чиноз тумани"),
    Tuman(165, 11, "Chirchiq shahri", "Чирчиқ шаҳри"),
    Tuman(166, 11, "Yuqori Chirchiq tumani", "Юқори Чирчиқ тумани"),
    Tuman(167, 11, "Yangiyo‘l tumani", "Янгийўл тумани"),
    Tuman(168, 12, "Beshariq tumani", "Бешариқ тумани"),
    Tuman(169, 12, "Bag‘dod tumani", "Бағдод тумани"),
    Tuman(170, 12, "Buvayda tumani", "Бувайда тумани"),
    Tuman(171, 12, "Dang‘ara tumani", "Данғара тумани"),
    Tuman(172, 12, "Yozyovon tumani", "Ёзёвон тумани"),
    Tuman(173, 12, "Quva tumani", "Қува тумани"),
    Tuman(174, 12, "Quvasoy shahri", "Қувасой шаҳри"),
    Tuman(175, 12, "Qo‘qon shahri", "Қўқон шаҳри"),
    Tuman(176, 12, "Qo‘shtepa tumani", "Қўштепа тумани"),
    Tuman(177, 12, "Marg‘ilon shahri", "Марғилон шаҳри"),
    Tuman(178, 12, "Oltiariq tumani", "Олтиариқ тумани"),
    Tuman(179, 12, "Rishton tumani", "Риштон тумани"),
    Tuman(180, 12, "So‘x tumani", "Сўх тумани"),
    Tuman(181, 12, "Toshloq tumani", "Тошлоқ тумани"),
    Tuman(182, 12, "Uchko‘prik tumani", "Учкўприк тумани"),
    Tuman(183, 12, "O‘zbekiston tumani", "Ўзбекистон тумани"),
    Tuman(184, 12, "Farg‘ona tumani", "Фарғона тумани"),
    Tuman(185, 12, "Farg‘ona shahri", "Фарғона шаҳри"),
    Tuman(186, 12, "Furqat tumani", "Фурқат тумани"),
    Tuman(187, 13, "Bog‘ot tumani", "Боғот тумани"),
    Tuman(188, 13, "Gurlan tumani", "Гурлан тумани"),
    Tuman(189, 13, "Qo‘shko‘pir tumani", "Қўшкўпир тумани"),
    Tuman(190, 13, "Urganch tumani", "Урганч тумани"),
    Tuman(191, 13, "Urganch shahri", "Урганч шаҳри"),
    Tuman(192, 13, "Xiva tumani", "Хива тумани"),
    Tuman(193, 13, "Hazorasp tumani", "Ҳазорасп тумани"),
    Tuman(194, 13, "Xonqa tumani", "Хонқа тумани"),
    Tuman(195, 13, "Shovot tumani", "Шовот тумани"),
    Tuman(196, 13, "Yangiariq tumani", "Янгиариқ тумани"),
    Tuman(197, 13, "Yangibozor tumani", "Янгибозор тумани"),
    Tuman(198, 14, "Bektemir tumani", "Бектемир тумани"),
    Tuman(199, 14, "Mirzo Ulug‘bek tumani", "Мирзо Улуғбек тумани"),
    Tuman(200, 14, "Mirobod tumani", "Миробод тумани"),
    Tuman(201, 14, "Olmazor tumani", "Олмазор тумани"),
    Tuman(202, 14, "Sergeli tumani", "Сергели тумани"),
    Tuman(203, 14, "Uchtepa tumani", "Учтепа тумани"),
    Tuman(204, 14, "Yashnobod tumani", "Яшнобод тумани"),
    Tuman(205, 14, "Chilonzor tumani", "Чилонзор тумани"),
    Tuman(206, 14, "Shayxontohur tumani", "Шайхонтоҳур тумани"),
    Tuman(207, 14, "Yunusobod tumani", "Юнусобод тумани"),
    Tuman(208, 14, "Yakkasaroy tumani", "Яккасарой тумани"),
    Tuman(209, 1, "Taxiatosh shahri", "Тахиатош шаҳри"),
    Tuman(210, 2, "Asaka shahri", "Асака шаҳри"),
    Tuman(211, 9, "Bandixon tumani", "Бандихон тумани"),
    Tuman(212, 11, "Ohangaron shahri", "Оҳангарон шаҳри"),
    Tuman(213, 11, "Yangiyo‘l shahri", "Янгийўл шаҳри"),
    Tuman(215, 11, "Toshkent tumani", "Тошкент тумани"),
    Tuman(216, 1, "Bo'zatov tumani", "Бўзатов тумани"),
    Tuman(217, 13, "Tuproqqal‘a tumani", "Тупроққалъа тумани"),
    Tuman(218, 5, "Ko'kdala tumani", "Кўкдала тумани"),
    Tuman(1001, 2, "Bo‘ston tumani", "Бўстон тумани"),
    Tuman(1002, 2, "Xo‘jaobod tumani", "Хўжаобод тумани"),
    Tuman(1003, 14, "Yangihayot tumani", "Янгиҳаёт тумани"),
)

fun findViloyatByName(name: String): Viloyat? =
    VILOYATS.firstOrNull { it.name == name || it.nameUz == name }

fun findTumanByName(name: String): Tuman? =
    TUMANS.firstOrNull { it.name == name || it.nameUz == name }

/** The tumans of one viloyat, or all of them when nothing is chosen yet. */
fun tumansOf(viloyatName: String): List<Tuman> {
    val v = findViloyatByName(viloyatName) ?: return TUMANS
    return TUMANS.filter { it.viloyatId == v.id }
}
