// One-shot generator for src/lib/regions/data.ts.
//
// Reads the raw kenjebaev/regions JSON (saved at the path below) and
// emits a typed TypeScript file with two arrays:
//   - VILOYATS    : 14 regions, Latin + Cyrillic
//   - TUMANS      : 203 districts, Latin + Cyrillic, with viloyatId FK
//
// Cyrillic for the 14 viloyats is hand-curated (overrides below).
// Cyrillic for the 203 tumans is generated by a rule-based Uzbek
// Latin → Cyrillic transliterator (multi-letter patterns processed
// first). The generated values are written into a normal .ts file
// so a reviewer can hand-correct any specific entry afterwards.
//
// Re-run with:
//   node scripts/generate-regions.js
// The output goes to stdout; redirect to src/lib/regions/data.ts.

const fs = require("fs");
const path = require("path");

const RAW_PATH = "C:/Users/aziz/AppData/Local/Temp/uz-regions.json";

const raw = JSON.parse(fs.readFileSync(RAW_PATH, "utf8"));

// ── Hand-curated viloyat Cyrillic (overrides the transliterator) ──
const VILOYAT_CYRILLIC = {
  "Qoraqalpog‘iston Respublikasi": "Қорақалпоғистон Республикаси",
  "Andijon viloyati":             "Андижон вилояти",
  "Buxoro viloyati":              "Бухоро вилояти",
  "Jizzax viloyati":              "Жиззах вилояти",
  "Qashqadaryo viloyati":         "Қашқадарё вилояти",
  "Navoiy viloyati":              "Навоий вилояти",
  "Namangan viloyati":            "Наманган вилояти",
  "Samarqand viloyati":           "Самарқанд вилояти",
  "Surxandaryo viloyati":         "Сурхандарё вилояти",
  "Sirdaryo viloyati":            "Сирдарё вилояти",
  "Toshkent viloyati":            "Тошкент вилояти",
  "Farg‘ona viloyati":            "Фарғона вилояти",
  "Xorazm viloyati":              "Хоразм вилояти",
  "Toshkent shahri":              "Тошкент шаҳри",
};

// ── Latin → Cyrillic transliterator ───────────────────────────────
// Multi-letter patterns first (longest match wins). The Uzbek
// orthography uses U+2018 (‘) for the special apostrophe in o' /
// g'; the older corpus also has backticks (`) and ASCII '. All
// three are normalised here.
const MULTI = [
  // Order matters — longer patterns first.
  ["sh",  "ш"], ["Sh",  "Ш"], ["SH",  "Ш"],
  ["ch",  "ч"], ["Ch",  "Ч"], ["CH",  "Ч"],
  ["g‘",  "ғ"], ["G‘",  "Ғ"],
  ["g'",  "ғ"], ["G'",  "Ғ"],
  ["g`",  "ғ"], ["G`",  "Ғ"],
  ["o‘",  "ў"], ["O‘",  "Ў"],
  ["o'",  "ў"], ["O'",  "Ў"],
  ["o`",  "ў"], ["O`",  "Ў"],
  ["yo",  "ё"], ["Yo",  "Ё"], ["YO",  "Ё"],
  ["yu",  "ю"], ["Yu",  "Ю"], ["YU",  "Ю"],
  ["ya",  "я"], ["Ya",  "Я"], ["YA",  "Я"],
];

const SINGLE = {
  a: "а", b: "б", d: "д", e: "е", f: "ф", g: "г", h: "ҳ",
  i: "и", j: "ж", k: "к", l: "л", m: "м", n: "н", o: "о",
  p: "п", q: "қ", r: "р", s: "с", t: "т", u: "у", v: "в",
  w: "в", x: "х", y: "й", z: "з",
  A: "А", B: "Б", D: "Д", E: "Е", F: "Ф", G: "Г", H: "Ҳ",
  I: "И", J: "Ж", K: "К", L: "Л", M: "М", N: "Н", O: "О",
  P: "П", Q: "Қ", R: "Р", S: "С", T: "Т", U: "У", V: "В",
  W: "В", X: "Х", Y: "Й", Z: "З",
};

function latinToCyrillic(input) {
  let s = input;
  // Apply multi-letter substitutions first.
  // Use a single pass per pattern; results don't contain Latin letters
  // so re-running patterns over the output is safe.
  for (const [from, to] of MULTI) {
    s = s.split(from).join(to);
  }
  // Now letter-by-letter for what's left.
  let out = "";
  for (const ch of s) {
    out += SINGLE[ch] ?? ch; // preserves spaces, digits, dashes, etc.
  }
  return out;
}

// ── Build VILOYATS ────────────────────────────────────────────────
const viloyats = raw.regions.map((r) => ({
  id: r.id,
  name: r.name,
  nameUz: VILOYAT_CYRILLIC[r.name] ?? latinToCyrillic(r.name),
}));

// ── Build TUMANS ─────────────────────────────────────────────────
const tumans = raw.districts.map((d) => ({
  id: d.id,
  viloyatId: d.region_id,
  name: d.name,
  nameUz: latinToCyrillic(d.name),
}));

// ── Emit TypeScript ──────────────────────────────────────────────
const ts = `// AUTO-GENERATED by scripts/generate-regions.js — do not edit by
// hand UNLESS you're correcting a specific entry's Cyrillic. The
// 14 viloyats have curated Cyrillic; the 203 tumans use a rule-
// based Uzbek Latin → Cyrillic transliteration (multi-letter
// patterns first). If you spot a wrong spelling, just edit the
// affected entry below — the next regeneration will overwrite the
// auto-generated values but you can move the override into the
// generator's VILOYAT_CYRILLIC / a TUMAN_CYRILLIC map.
//
// Source: kenjebaev/regions \`regions.json\` (14 viloyats + 203 tumans).

export interface Viloyat {
  id: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Hand-curated Cyrillic name. */
  nameUz: string;
}

export interface Tuman {
  id: number;
  viloyatId: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Rule-transliterated Cyrillic name. */
  nameUz: string;
}

export const VILOYATS: readonly Viloyat[] = ${JSON.stringify(viloyats, null, 2)} as const;

export const TUMANS: readonly Tuman[] = ${JSON.stringify(tumans, null, 2)} as const;
`;

process.stdout.write(ts);
