// One-shot generator for src/lib/regions/data.ts.
//
// Reads the raw kenjebaev/regions JSON (saved at the path below) and
// emits a typed TypeScript file with two arrays:
//   - VILOYATS    : 14 regions, Latin + Cyrillic
//   - TUMANS      : 203 districts, Latin + Cyrillic, with viloyatId FK
//
// Cyrillic for the 14 viloyats is hand-curated (overrides below).
// Cyrillic for the 203 tumans is generated by a rule-based Uzbek
// Latin → Cyrillic transliterator (multi-letter patterns processed
// first). The generated values are written into a normal .ts file
// so a reviewer can hand-correct any specific entry afterwards.
//
// Re-run with:
//   node scripts/generate-regions.js
// The output goes to stdout; redirect to src/lib/regions/data.ts.

const fs = require("fs");
const path = require("path");

const RAW_PATH = "C:/Users/aziz/AppData/Local/Temp/uz-regions.json";

const raw = JSON.parse(fs.readFileSync(RAW_PATH, "utf8"));

// ── Viloyat overrides (both Latin and Cyrillic, like districts) ──
//
// Keyed by the ORIGINAL kenjebaev `name` so future regenerations are
// stable. Each entry supplies the displayed `name` and `nameUz`.
// Currently the only Latin rename is `Surxandaryo viloyati` →
// `Surxondaryo viloyati` (the spelling the rest of the CRM uses) —
// every other viloyat keeps its kenjebaev Latin form.
const VILOYAT_OVERRIDES = {
  "Qoraqalpog‘iston Respublikasi": { name: "Qoraqalpog‘iston Respublikasi", nameUz: "Қорақалпоғистон Республикаси" },
  "Andijon viloyati":              { name: "Andijon viloyati",              nameUz: "Андижон вилояти"               },
  "Buxoro viloyati":               { name: "Buxoro viloyati",               nameUz: "Бухоро вилояти"                },
  "Jizzax viloyati":               { name: "Jizzax viloyati",               nameUz: "Жиззах вилояти"                },
  "Qashqadaryo viloyati":          { name: "Qashqadaryo viloyati",          nameUz: "Қашқадарё вилояти"             },
  "Navoiy viloyati":               { name: "Navoiy viloyati",               nameUz: "Навоий вилояти"                },
  "Namangan viloyati":             { name: "Namangan viloyati",             nameUz: "Наманган вилояти"              },
  "Samarqand viloyati":            { name: "Samarqand viloyati",            nameUz: "Самарқанд вилояти"             },
  "Surxandaryo viloyati":          { name: "Surxondaryo viloyati",          nameUz: "Сурхондарё вилояти"            },
  "Sirdaryo viloyati":             { name: "Sirdaryo viloyati",             nameUz: "Сирдарё вилояти"               },
  "Toshkent viloyati":             { name: "Toshkent viloyati",             nameUz: "Тошкент вилояти"               },
  "Farg‘ona viloyati":             { name: "Farg‘ona viloyati",             nameUz: "Фарғона вилояти"               },
  "Xorazm viloyati":               { name: "Xorazm viloyati",               nameUz: "Хоразм вилояти"                },
  "Toshkent shahri":               { name: "Toshkent shahri",               nameUz: "Тошкент шаҳри"                 },
};

// ── District (tuman / shahri) overrides ──
//
// Two purposes:
//   1. Fix Latin typos in the kenjebaev source (e.g. "Angiren" → "Angren",
//      "Bekabod" → "Bekobod", abbreviated "M.Ulug‘bek" → full "Mirzo
//      Ulug‘bek") so what we show operators matches the canonical names
//      from Wikipedia / lex.uz / official viloyat sites.
//   2. Override the rule-based Cyrillic when the rules don't produce the
//      standard Uzbek-Cyrillic spelling — most often word-initial Э (vs.
//      Е), or a glottal-stop apostrophe `‘` that should be `ъ` in
//      Cyrillic.
//
// Keyed by the ORIGINAL kenjebaev name so future regenerations stay
// stable even if the override's Latin replacement changes the displayed
// form. Both `name` and `nameUz` are emitted into the typed constant.
const DISTRICT_OVERRIDES = {
  // ── Glottal-stop / spelling fixes inside an otherwise-correct name
  "Ellikqal‘a tumani":   { name: "Ellikqal‘a tumani",   nameUz: "Элликқалъа тумани"     },
  "Tuproqqala tumani":   { name: "Tuproqqal‘a tumani",  nameUz: "Тупроққалъа тумани"   },

  // ── Latin typos in kenjebaev — fixed to Wikipedia/lex.uz canonical
  "Angiren shahri":        { name: "Angren shahri",         nameUz: "Ангрен шаҳри"          },
  "Bekabod shahri":        { name: "Bekobod shahri",        nameUz: "Бекобод шаҳри"         },
  "Bekabod tumani":        { name: "Bekobod tumani",        nameUz: "Бекобод тумани"        },
  "Kegayli tumani":        { name: "Kegeyli tumani",        nameUz: "Кегейли тумани"        },
  "Qonliko‘l tumani":      { name: "Qanliko‘l tumani",      nameUz: "Қанликўл тумани"       },
  "CHimboy tumani":        { name: "Chimboy tumani",        nameUz: "Чимбой тумани"         },
  "SHumanay tumani":       { name: "Shumanay tumani",       nameUz: "Шуманай тумани"        },
  "Izbosgan tumani":       { name: "Izboskan tumani",       nameUz: "Избоскан тумани"       },
  "Nurabod tumani":        { name: "Nurobod tumani",        nameUz: "Нуробод тумани"        },
  "Pastarg‘om tumani":     { name: "Pastdarg‘om tumani",    nameUz: "Пастдарғом тумани"     },
  "Qo‘mqo‘rg‘on tumani":   { name: "Qumqo‘rg‘on tumani",    nameUz: "Қумқўрғон тумани"      },
  "Sariosiy tumani":       { name: "Sariosiyo tumani",      nameUz: "Сариосиё тумани"       },
  "Xavos tumani":          { name: "Xovos tumani",          nameUz: "Ховос тумани"          },
  "Quyichirchiq tumani":   { name: "Quyi Chirchiq tumani",  nameUz: "Қуйи Чирчиқ тумани"    },
  "O‘rtachirchiq tumani":  { name: "O‘rta Chirchiq tumani", nameUz: "Ўрта Чирчиқ тумани"    },
  "Yuqorichirchiq tumani": { name: "Yuqori Chirchiq tumani",nameUz: "Юқори Чирчиқ тумани"   },
  "Bog‘dod tumani":        { name: "Bag‘dod tumani",        nameUz: "Бағдод тумани"         },
  "Xazarasp tumani":       { name: "Hazorasp tumani",       nameUz: "Ҳазорасп тумани"       },
  "Shavot tumani":         { name: "Shovot tumani",         nameUz: "Шовот тумани"          },
  "Bektimer tumani":       { name: "Bektemir tumani",       nameUz: "Бектемир тумани"       },

  // ── Abbreviated → full personal-name tumans (per Wikipedia / lex.uz)
  "M.Ulug‘bek tumani":     { name: "Mirzo Ulug‘bek tumani", nameUz: "Мирзо Улуғбек тумани"  },
  "Sh.Rashidov tumani":    { name: "Sharof Rashidov tumani",nameUz: "Шароф Рашидов тумани"  },
};

// ── Latin → Cyrillic transliterator ───────────────────────────────
// Multi-letter patterns first (longest match wins). The Uzbek
// orthography uses U+2018 (‘) for the special apostrophe in o' /
// g'; the older corpus also has backticks (`) and ASCII '. All
// three are normalised here.
const MULTI = [
  // Order matters — longer patterns first.
  ["sh",  "ш"], ["Sh",  "Ш"], ["SH",  "Ш"],
  ["ch",  "ч"], ["Ch",  "Ч"], ["CH",  "Ч"],
  ["g‘",  "ғ"], ["G‘",  "Ғ"],
  ["g'",  "ғ"], ["G'",  "Ғ"],
  ["g`",  "ғ"], ["G`",  "Ғ"],
  ["o‘",  "ў"], ["O‘",  "Ў"],
  ["o'",  "ў"], ["O'",  "Ў"],
  ["o`",  "ў"], ["O`",  "Ў"],
  ["yo",  "ё"], ["Yo",  "Ё"], ["YO",  "Ё"],
  ["yu",  "ю"], ["Yu",  "Ю"], ["YU",  "Ю"],
  ["ya",  "я"], ["Ya",  "Я"], ["YA",  "Я"],
];

const SINGLE = {
  a: "а", b: "б", d: "д", e: "е", f: "ф", g: "г", h: "ҳ",
  i: "и", j: "ж", k: "к", l: "л", m: "м", n: "н", o: "о",
  p: "п", q: "қ", r: "р", s: "с", t: "т", u: "у", v: "в",
  w: "в", x: "х", y: "й", z: "з",
  A: "А", B: "Б", D: "Д", E: "Е", F: "Ф", G: "Г", H: "Ҳ",
  I: "И", J: "Ж", K: "К", L: "Л", M: "М", N: "Н", O: "О",
  P: "П", Q: "Қ", R: "Р", S: "С", T: "Т", U: "У", V: "В",
  W: "В", X: "Х", Y: "Й", Z: "З",
};

function latinToCyrillic(input) {
  let s = input;
  // Apply multi-letter substitutions first.
  // Use a single pass per pattern; results don't contain Latin letters
  // so re-running patterns over the output is safe.
  for (const [from, to] of MULTI) {
    s = s.split(from).join(to);
  }
  // Now letter-by-letter for what's left.
  let out = "";
  for (const ch of s) {
    out += SINGLE[ch] ?? ch; // preserves spaces, digits, dashes, etc.
  }
  return out;
}

// ── Build VILOYATS ────────────────────────────────────────────────
const viloyats = raw.regions.map((r) => {
  const override = VILOYAT_OVERRIDES[r.name];
  return {
    id: r.id,
    name: override?.name ?? r.name,
    nameUz: override?.nameUz ?? latinToCyrillic(r.name),
  };
});

// ── Build TUMANS ─────────────────────────────────────────────────
const tumans = raw.districts.map((d) => {
  const override = DISTRICT_OVERRIDES[d.name];
  return {
    id: d.id,
    viloyatId: d.region_id,
    name: override?.name ?? d.name,
    nameUz: override?.nameUz ?? latinToCyrillic(d.name),
  };
});

// ── Tumans missing from the kenjebaev snapshot ──────────────────
//
// Appended after the kenjebaev rows so the original IDs stay
// untouched. IDs start at 1001 (well above kenjebaev's district id
// range, 15..218) so adding rows in the future won't collide.
// Verified against Wikipedia + lex.uz for spelling and viloyatId.
const EXTRA_TUMANS = [
  // Andijon viloyati (region id = 2). kenjebaev has "Bo‘z tumani"
  // and "Xonabod tumani" (both real, post-2018 splits) but is
  // missing these two long-standing ones.
  { id: 1001, viloyatId: 2,  name: "Bo‘ston tumani",   nameUz: "Бўстон тумани"   },
  { id: 1002, viloyatId: 2,  name: "Xo‘jaobod tumani", nameUz: "Хўжаобод тумани" },
  // Toshkent shahri (region id = 14). Created in 2020 by splitting
  // off from Sergeli + Yashnobod, so it's absent in the kenjebaev
  // snapshot.
  { id: 1003, viloyatId: 14, name: "Yangihayot tumani", nameUz: "Янгиҳаёт тумани" },
];
tumans.push(...EXTRA_TUMANS);

// ── Emit TypeScript ──────────────────────────────────────────────
const ts = `// AUTO-GENERATED by scripts/generate-regions.js — do not edit by
// hand UNLESS you're correcting a specific entry's Cyrillic. The
// 14 viloyats have curated Cyrillic; the 203 tumans use a rule-
// based Uzbek Latin → Cyrillic transliteration (multi-letter
// patterns first). If you spot a wrong spelling, just edit the
// affected entry below — the next regeneration will overwrite the
// auto-generated values but you can move the override into the
// generator's VILOYAT_CYRILLIC / a TUMAN_CYRILLIC map.
//
// Source: kenjebaev/regions \`regions.json\` (14 viloyats + 203 tumans).

export interface Viloyat {
  id: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Hand-curated Cyrillic name. */
  nameUz: string;
}

export interface Tuman {
  id: number;
  viloyatId: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Rule-transliterated Cyrillic name. */
  nameUz: string;
}

export const VILOYATS: readonly Viloyat[] = ${JSON.stringify(viloyats, null, 2)} as const;

export const TUMANS: readonly Tuman[] = ${JSON.stringify(tumans, null, 2)} as const;
`;

process.stdout.write(ts);
