// AUTO-GENERATED by scripts/generate-regions.js — do not edit by
// hand UNLESS you're correcting a specific entry's Cyrillic. The
// 14 viloyats have curated Cyrillic; the 203 tumans use a rule-
// based Uzbek Latin → Cyrillic transliteration (multi-letter
// patterns first). If you spot a wrong spelling, just edit the
// affected entry below — the next regeneration will overwrite the
// auto-generated values but you can move the override into the
// generator's VILOYAT_CYRILLIC / a TUMAN_CYRILLIC map.
//
// Source: kenjebaev/regions `regions.json` (14 viloyats + 203 tumans).

export interface Viloyat {
  id: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Hand-curated Cyrillic name. */
  nameUz: string;
}

export interface Tuman {
  id: number;
  viloyatId: number;
  /** Latin name as it appears in the kenjebaev source. */
  name: string;
  /** Rule-transliterated Cyrillic name. */
  nameUz: string;
}

export const VILOYATS: readonly Viloyat[] = [
  {
    "id": 1,
    "name": "Qoraqalpog‘iston Respublikasi",
    "nameUz": "Қорақалпоғистон Республикаси"
  },
  {
    "id": 2,
    "name": "Andijon viloyati",
    "nameUz": "Андижон вилояти"
  },
  {
    "id": 3,
    "name": "Buxoro viloyati",
    "nameUz": "Бухоро вилояти"
  },
  {
    "id": 4,
    "name": "Jizzax viloyati",
    "nameUz": "Жиззах вилояти"
  },
  {
    "id": 5,
    "name": "Qashqadaryo viloyati",
    "nameUz": "Қашқадарё вилояти"
  },
  {
    "id": 6,
    "name": "Navoiy viloyati",
    "nameUz": "Навоий вилояти"
  },
  {
    "id": 7,
    "name": "Namangan viloyati",
    "nameUz": "Наманган вилояти"
  },
  {
    "id": 8,
    "name": "Samarqand viloyati",
    "nameUz": "Самарқанд вилояти"
  },
  {
    "id": 9,
    "name": "Surxondaryo viloyati",
    "nameUz": "Сурхондарё вилояти"
  },
  {
    "id": 10,
    "name": "Sirdaryo viloyati",
    "nameUz": "Сирдарё вилояти"
  },
  {
    "id": 11,
    "name": "Toshkent viloyati",
    "nameUz": "Тошкент вилояти"
  },
  {
    "id": 12,
    "name": "Farg‘ona viloyati",
    "nameUz": "Фарғона вилояти"
  },
  {
    "id": 13,
    "name": "Xorazm viloyati",
    "nameUz": "Хоразм вилояти"
  },
  {
    "id": 14,
    "name": "Toshkent shahri",
    "nameUz": "Тошкент шаҳри"
  }
] as const;

export const TUMANS: readonly Tuman[] = [
  {
    "id": 15,
    "viloyatId": 1,
    "name": "Amudaryo tumani",
    "nameUz": "Амударё тумани"
  },
  {
    "id": 16,
    "viloyatId": 1,
    "name": "Beruniy tumani",
    "nameUz": "Беруний тумани"
  },
  {
    "id": 17,
    "viloyatId": 1,
    "name": "Kegeyli tumani",
    "nameUz": "Кегейли тумани"
  },
  {
    "id": 18,
    "viloyatId": 1,
    "name": "Qanliko‘l tumani",
    "nameUz": "Қанликўл тумани"
  },
  {
    "id": 19,
    "viloyatId": 1,
    "name": "Qorao‘zak tumani",
    "nameUz": "Қораўзак тумани"
  },
  {
    "id": 20,
    "viloyatId": 1,
    "name": "Qo‘ng‘irot tumani",
    "nameUz": "Қўнғирот тумани"
  },
  {
    "id": 21,
    "viloyatId": 1,
    "name": "Mo‘ynoq tumani",
    "nameUz": "Мўйноқ тумани"
  },
  {
    "id": 22,
    "viloyatId": 1,
    "name": "Nukus tumani",
    "nameUz": "Нукус тумани"
  },
  {
    "id": 23,
    "viloyatId": 1,
    "name": "Nukus shahri",
    "nameUz": "Нукус шаҳри"
  },
  {
    "id": 24,
    "viloyatId": 1,
    "name": "Taxtako‘pir tumani",
    "nameUz": "Тахтакўпир тумани"
  },
  {
    "id": 25,
    "viloyatId": 1,
    "name": "To‘rtko‘l tumani",
    "nameUz": "Тўрткўл тумани"
  },
  {
    "id": 26,
    "viloyatId": 1,
    "name": "Xo‘jayli tumani",
    "nameUz": "Хўжайли тумани"
  },
  {
    "id": 27,
    "viloyatId": 1,
    "name": "Chimboy tumani",
    "nameUz": "Чимбой тумани"
  },
  {
    "id": 28,
    "viloyatId": 1,
    "name": "Shumanay tumani",
    "nameUz": "Шуманай тумани"
  },
  {
    "id": 29,
    "viloyatId": 1,
    "name": "Ellikqal‘a tumani",
    "nameUz": "Элликқалъа тумани"
  },
  {
    "id": 30,
    "viloyatId": 2,
    "name": "Andijon shahri",
    "nameUz": "Андижон шаҳри"
  },
  {
    "id": 31,
    "viloyatId": 2,
    "name": "Andijon tumani",
    "nameUz": "Андижон тумани"
  },
  {
    "id": 32,
    "viloyatId": 2,
    "name": "Asaka tumani",
    "nameUz": "Асака тумани"
  },
  {
    "id": 33,
    "viloyatId": 2,
    "name": "Baliqchi tumani",
    "nameUz": "Балиқчи тумани"
  },
  {
    "id": 34,
    "viloyatId": 2,
    "name": "Buloqboshi tumani",
    "nameUz": "Булоқбоши тумани"
  },
  {
    "id": 35,
    "viloyatId": 2,
    "name": "Bo‘z tumani",
    "nameUz": "Бўз тумани"
  },
  {
    "id": 36,
    "viloyatId": 2,
    "name": "Jalaquduq tumani",
    "nameUz": "Жалақудуқ тумани"
  },
  {
    "id": 37,
    "viloyatId": 2,
    "name": "Izboskan tumani",
    "nameUz": "Избоскан тумани"
  },
  {
    "id": 38,
    "viloyatId": 2,
    "name": "Qorasuv shahri",
    "nameUz": "Қорасув шаҳри"
  },
  {
    "id": 39,
    "viloyatId": 2,
    "name": "Qo‘rg‘ontepa tumani",
    "nameUz": "Қўрғонтепа тумани"
  },
  {
    "id": 40,
    "viloyatId": 2,
    "name": "Marhamat tumani",
    "nameUz": "Марҳамат тумани"
  },
  {
    "id": 41,
    "viloyatId": 2,
    "name": "Oltinko‘l tumani",
    "nameUz": "Олтинкўл тумани"
  },
  {
    "id": 42,
    "viloyatId": 2,
    "name": "Paxtaobod tumani",
    "nameUz": "Пахтаобод тумани"
  },
  {
    "id": 43,
    "viloyatId": 2,
    "name": "Ulug‘nor tumani",
    "nameUz": "Улуғнор тумани"
  },
  {
    "id": 44,
    "viloyatId": 2,
    "name": "Xonabod tumani",
    "nameUz": "Хонабод тумани"
  },
  {
    "id": 45,
    "viloyatId": 2,
    "name": "Xo‘jaobod shahri",
    "nameUz": "Хўжаобод шаҳри"
  },
  {
    "id": 46,
    "viloyatId": 2,
    "name": "Shahrixon tumani",
    "nameUz": "Шаҳрихон тумани"
  },
  {
    "id": 47,
    "viloyatId": 3,
    "name": "Buxoro shahri",
    "nameUz": "Бухоро шаҳри"
  },
  {
    "id": 48,
    "viloyatId": 3,
    "name": "Buxoro tumani",
    "nameUz": "Бухоро тумани"
  },
  {
    "id": 49,
    "viloyatId": 3,
    "name": "Vobkent tumani",
    "nameUz": "Вобкент тумани"
  },
  {
    "id": 50,
    "viloyatId": 3,
    "name": "G‘ijduvon tumani",
    "nameUz": "Ғиждувон тумани"
  },
  {
    "id": 51,
    "viloyatId": 3,
    "name": "Jondor tumani",
    "nameUz": "Жондор тумани"
  },
  {
    "id": 52,
    "viloyatId": 3,
    "name": "Kogon tumani",
    "nameUz": "Когон тумани"
  },
  {
    "id": 53,
    "viloyatId": 3,
    "name": "Kogon shahri",
    "nameUz": "Когон шаҳри"
  },
  {
    "id": 54,
    "viloyatId": 3,
    "name": "Qorako‘l tumani",
    "nameUz": "Қоракўл тумани"
  },
  {
    "id": 55,
    "viloyatId": 3,
    "name": "Qorovulbozor tumani",
    "nameUz": "Қоровулбозор тумани"
  },
  {
    "id": 56,
    "viloyatId": 3,
    "name": "Olot tumani",
    "nameUz": "Олот тумани"
  },
  {
    "id": 57,
    "viloyatId": 3,
    "name": "Peshku tumani",
    "nameUz": "Пешку тумани"
  },
  {
    "id": 58,
    "viloyatId": 3,
    "name": "Romitan tumani",
    "nameUz": "Ромитан тумани"
  },
  {
    "id": 59,
    "viloyatId": 3,
    "name": "Shofirkon tumani",
    "nameUz": "Шофиркон тумани"
  },
  {
    "id": 60,
    "viloyatId": 4,
    "name": "Arnasoy tumani",
    "nameUz": "Арнасой тумани"
  },
  {
    "id": 61,
    "viloyatId": 4,
    "name": "Baxmal tumani",
    "nameUz": "Бахмал тумани"
  },
  {
    "id": 62,
    "viloyatId": 4,
    "name": "G‘allaorol tumani",
    "nameUz": "Ғаллаорол тумани"
  },
  {
    "id": 63,
    "viloyatId": 4,
    "name": "Do‘stlik tumani",
    "nameUz": "Дўстлик тумани"
  },
  {
    "id": 64,
    "viloyatId": 4,
    "name": "Sharof Rashidov tumani",
    "nameUz": "Шароф Рашидов тумани"
  },
  {
    "id": 65,
    "viloyatId": 4,
    "name": "Jizzax shahri",
    "nameUz": "Жиззах шаҳри"
  },
  {
    "id": 66,
    "viloyatId": 4,
    "name": "Zarbdor tumani",
    "nameUz": "Зарбдор тумани"
  },
  {
    "id": 67,
    "viloyatId": 4,
    "name": "Zafarobod tumani",
    "nameUz": "Зафаробод тумани"
  },
  {
    "id": 68,
    "viloyatId": 4,
    "name": "Zomin tumani",
    "nameUz": "Зомин тумани"
  },
  {
    "id": 69,
    "viloyatId": 4,
    "name": "Mirzacho‘l tumani",
    "nameUz": "Мирзачўл тумани"
  },
  {
    "id": 70,
    "viloyatId": 4,
    "name": "Paxtakor tumani",
    "nameUz": "Пахтакор тумани"
  },
  {
    "id": 71,
    "viloyatId": 4,
    "name": "Forish tumani",
    "nameUz": "Фориш тумани"
  },
  {
    "id": 72,
    "viloyatId": 4,
    "name": "Yangiobod tumani",
    "nameUz": "Янгиобод тумани"
  },
  {
    "id": 73,
    "viloyatId": 5,
    "name": "G‘uzor tumani",
    "nameUz": "Ғузор тумани"
  },
  {
    "id": 74,
    "viloyatId": 5,
    "name": "Dehqonobod tumani",
    "nameUz": "Деҳқонобод тумани"
  },
  {
    "id": 75,
    "viloyatId": 5,
    "name": "Qamashi tumani",
    "nameUz": "Қамаши тумани"
  },
  {
    "id": 76,
    "viloyatId": 5,
    "name": "Qarshi tumani",
    "nameUz": "Қарши тумани"
  },
  {
    "id": 77,
    "viloyatId": 5,
    "name": "Qarshi shahri",
    "nameUz": "Қарши шаҳри"
  },
  {
    "id": 78,
    "viloyatId": 5,
    "name": "Kasbi tumani",
    "nameUz": "Касби тумани"
  },
  {
    "id": 79,
    "viloyatId": 5,
    "name": "Kitob tumani",
    "nameUz": "Китоб тумани"
  },
  {
    "id": 80,
    "viloyatId": 5,
    "name": "Koson tumani",
    "nameUz": "Косон тумани"
  },
  {
    "id": 81,
    "viloyatId": 5,
    "name": "Mirishkor tumani",
    "nameUz": "Миришкор тумани"
  },
  {
    "id": 82,
    "viloyatId": 5,
    "name": "Muborak tumani",
    "nameUz": "Муборак тумани"
  },
  {
    "id": 83,
    "viloyatId": 5,
    "name": "Nishon tumani",
    "nameUz": "Нишон тумани"
  },
  {
    "id": 84,
    "viloyatId": 5,
    "name": "Chiroqchi tumani",
    "nameUz": "Чироқчи тумани"
  },
  {
    "id": 85,
    "viloyatId": 5,
    "name": "Shahrisabz tumani",
    "nameUz": "Шаҳрисабз тумани"
  },
  {
    "id": 86,
    "viloyatId": 5,
    "name": "Yakkabog‘ tumani",
    "nameUz": "Яккабоғ тумани"
  },
  {
    "id": 87,
    "viloyatId": 6,
    "name": "Zarafshon shahri",
    "nameUz": "Зарафшон шаҳри"
  },
  {
    "id": 88,
    "viloyatId": 6,
    "name": "Karmana tumani",
    "nameUz": "Кармана тумани"
  },
  {
    "id": 89,
    "viloyatId": 6,
    "name": "Qiziltepa tumani",
    "nameUz": "Қизилтепа тумани"
  },
  {
    "id": 90,
    "viloyatId": 6,
    "name": "Konimex tumani",
    "nameUz": "Конимех тумани"
  },
  {
    "id": 91,
    "viloyatId": 6,
    "name": "Navbahor tumani",
    "nameUz": "Навбаҳор тумани"
  },
  {
    "id": 92,
    "viloyatId": 6,
    "name": "Navoiy shahri",
    "nameUz": "Навоий шаҳри"
  },
  {
    "id": 93,
    "viloyatId": 6,
    "name": "Nurota tumani",
    "nameUz": "Нурота тумани"
  },
  {
    "id": 94,
    "viloyatId": 6,
    "name": "Tomdi tumani",
    "nameUz": "Томди тумани"
  },
  {
    "id": 95,
    "viloyatId": 6,
    "name": "Uchquduq tumani",
    "nameUz": "Учқудуқ тумани"
  },
  {
    "id": 96,
    "viloyatId": 6,
    "name": "Xatirchi tumani",
    "nameUz": "Хатирчи тумани"
  },
  {
    "id": 97,
    "viloyatId": 7,
    "name": "Kosonsoy tumani",
    "nameUz": "Косонсой тумани"
  },
  {
    "id": 98,
    "viloyatId": 7,
    "name": "Mingbuloq tumani",
    "nameUz": "Мингбулоқ тумани"
  },
  {
    "id": 99,
    "viloyatId": 7,
    "name": "Namangan tumani",
    "nameUz": "Наманган тумани"
  },
  {
    "id": 100,
    "viloyatId": 7,
    "name": "Namangan shahri",
    "nameUz": "Наманган шаҳри"
  },
  {
    "id": 101,
    "viloyatId": 7,
    "name": "Norin tumani",
    "nameUz": "Норин тумани"
  },
  {
    "id": 102,
    "viloyatId": 7,
    "name": "Pop tumani",
    "nameUz": "Поп тумани"
  },
  {
    "id": 103,
    "viloyatId": 7,
    "name": "To‘raqo‘rg‘on tumani",
    "nameUz": "Тўрақўрғон тумани"
  },
  {
    "id": 104,
    "viloyatId": 7,
    "name": "Uychi tumani",
    "nameUz": "Уйчи тумани"
  },
  {
    "id": 105,
    "viloyatId": 7,
    "name": "Uchqo‘rg‘on tumani",
    "nameUz": "Учқўрғон тумани"
  },
  {
    "id": 106,
    "viloyatId": 7,
    "name": "Chortoq tumani",
    "nameUz": "Чортоқ тумани"
  },
  {
    "id": 107,
    "viloyatId": 7,
    "name": "Chust tumani",
    "nameUz": "Чуст тумани"
  },
  {
    "id": 108,
    "viloyatId": 7,
    "name": "Yangiqo‘rg‘on tumani",
    "nameUz": "Янгиқўрғон тумани"
  },
  {
    "id": 109,
    "viloyatId": 8,
    "name": "Bulung‘ur tumani",
    "nameUz": "Булунғур тумани"
  },
  {
    "id": 110,
    "viloyatId": 8,
    "name": "Jomboy tumani",
    "nameUz": "Жомбой тумани"
  },
  {
    "id": 111,
    "viloyatId": 8,
    "name": "Ishtixon tumani",
    "nameUz": "Иштихон тумани"
  },
  {
    "id": 112,
    "viloyatId": 8,
    "name": "Kattaqo‘rg‘on tumani",
    "nameUz": "Каттақўрғон тумани"
  },
  {
    "id": 113,
    "viloyatId": 8,
    "name": "Kattaqo‘rg‘on shahri",
    "nameUz": "Каттақўрғон шаҳри"
  },
  {
    "id": 114,
    "viloyatId": 8,
    "name": "Qo‘shrabot tumani",
    "nameUz": "Қўшработ тумани"
  },
  {
    "id": 115,
    "viloyatId": 8,
    "name": "Narpay tumani",
    "nameUz": "Нарпай тумани"
  },
  {
    "id": 116,
    "viloyatId": 8,
    "name": "Nurobod tumani",
    "nameUz": "Нуробод тумани"
  },
  {
    "id": 117,
    "viloyatId": 8,
    "name": "Oqdaryo tumani",
    "nameUz": "Оқдарё тумани"
  },
  {
    "id": 118,
    "viloyatId": 8,
    "name": "Payariq tumani",
    "nameUz": "Паяриқ тумани"
  },
  {
    "id": 119,
    "viloyatId": 8,
    "name": "Pastdarg‘om tumani",
    "nameUz": "Пастдарғом тумани"
  },
  {
    "id": 120,
    "viloyatId": 8,
    "name": "Paxtachi tumani",
    "nameUz": "Пахтачи тумани"
  },
  {
    "id": 121,
    "viloyatId": 8,
    "name": "Samarqand tumani",
    "nameUz": "Самарқанд тумани"
  },
  {
    "id": 122,
    "viloyatId": 8,
    "name": "Samarqand shahri",
    "nameUz": "Самарқанд шаҳри"
  },
  {
    "id": 123,
    "viloyatId": 8,
    "name": "Toyloq tumani",
    "nameUz": "Тойлоқ тумани"
  },
  {
    "id": 124,
    "viloyatId": 8,
    "name": "Urgut tumani",
    "nameUz": "Ургут тумани"
  },
  {
    "id": 125,
    "viloyatId": 9,
    "name": "Angor tumani",
    "nameUz": "Ангор тумани"
  },
  {
    "id": 126,
    "viloyatId": 9,
    "name": "Boysun tumani",
    "nameUz": "Бойсун тумани"
  },
  {
    "id": 127,
    "viloyatId": 9,
    "name": "Denov tumani",
    "nameUz": "Денов тумани"
  },
  {
    "id": 128,
    "viloyatId": 9,
    "name": "Jarqo‘rg‘on tumani",
    "nameUz": "Жарқўрғон тумани"
  },
  {
    "id": 129,
    "viloyatId": 9,
    "name": "Qiziriq tumani",
    "nameUz": "Қизириқ тумани"
  },
  {
    "id": 130,
    "viloyatId": 9,
    "name": "Qumqo‘rg‘on tumani",
    "nameUz": "Қумқўрғон тумани"
  },
  {
    "id": 131,
    "viloyatId": 9,
    "name": "Muzrabot tumani",
    "nameUz": "Музработ тумани"
  },
  {
    "id": 132,
    "viloyatId": 9,
    "name": "Oltinsoy tumani",
    "nameUz": "Олтинсой тумани"
  },
  {
    "id": 133,
    "viloyatId": 9,
    "name": "Sariosiyo tumani",
    "nameUz": "Сариосиё тумани"
  },
  {
    "id": 134,
    "viloyatId": 9,
    "name": "Termiz tumani",
    "nameUz": "Термиз тумани"
  },
  {
    "id": 135,
    "viloyatId": 9,
    "name": "Termiz shahri",
    "nameUz": "Термиз шаҳри"
  },
  {
    "id": 136,
    "viloyatId": 9,
    "name": "Uzun tumani",
    "nameUz": "Узун тумани"
  },
  {
    "id": 137,
    "viloyatId": 9,
    "name": "Sherobod tumani",
    "nameUz": "Шеробод тумани"
  },
  {
    "id": 138,
    "viloyatId": 9,
    "name": "Sho‘rchi tumani",
    "nameUz": "Шўрчи тумани"
  },
  {
    "id": 139,
    "viloyatId": 10,
    "name": "Boyovut tumani",
    "nameUz": "Боёвут тумани"
  },
  {
    "id": 140,
    "viloyatId": 10,
    "name": "Guliston tumani",
    "nameUz": "Гулистон тумани"
  },
  {
    "id": 141,
    "viloyatId": 10,
    "name": "Guliston shahri",
    "nameUz": "Гулистон шаҳри"
  },
  {
    "id": 142,
    "viloyatId": 10,
    "name": "Mirzaobod tumani",
    "nameUz": "Мирзаобод тумани"
  },
  {
    "id": 143,
    "viloyatId": 10,
    "name": "Oqoltin tumani",
    "nameUz": "Оқолтин тумани"
  },
  {
    "id": 144,
    "viloyatId": 10,
    "name": "Sayxunobod tumani",
    "nameUz": "Сайхунобод тумани"
  },
  {
    "id": 145,
    "viloyatId": 10,
    "name": "Sardoba tumani",
    "nameUz": "Сардоба тумани"
  },
  {
    "id": 146,
    "viloyatId": 10,
    "name": "Sirdaryo tumani",
    "nameUz": "Сирдарё тумани"
  },
  {
    "id": 147,
    "viloyatId": 10,
    "name": "Xovos tumani",
    "nameUz": "Ховос тумани"
  },
  {
    "id": 148,
    "viloyatId": 10,
    "name": "Shirin shahri",
    "nameUz": "Ширин шаҳри"
  },
  {
    "id": 149,
    "viloyatId": 10,
    "name": "Yangier shahri",
    "nameUz": "Янгиер шаҳри"
  },
  {
    "id": 150,
    "viloyatId": 11,
    "name": "Angren shahri",
    "nameUz": "Ангрен шаҳри"
  },
  {
    "id": 151,
    "viloyatId": 11,
    "name": "Bekobod tumani",
    "nameUz": "Бекобод тумани"
  },
  {
    "id": 152,
    "viloyatId": 11,
    "name": "Bekobod shahri",
    "nameUz": "Бекобод шаҳри"
  },
  {
    "id": 153,
    "viloyatId": 11,
    "name": "Bo‘ka tumani",
    "nameUz": "Бўка тумани"
  },
  {
    "id": 154,
    "viloyatId": 11,
    "name": "Bo‘stonliq tumani",
    "nameUz": "Бўстонлиқ тумани"
  },
  {
    "id": 155,
    "viloyatId": 11,
    "name": "Zangiota tumani",
    "nameUz": "Зангиота тумани"
  },
  {
    "id": 156,
    "viloyatId": 11,
    "name": "Qibray tumani",
    "nameUz": "Қибрай тумани"
  },
  {
    "id": 157,
    "viloyatId": 11,
    "name": "Quyi Chirchiq tumani",
    "nameUz": "Қуйи Чирчиқ тумани"
  },
  {
    "id": 158,
    "viloyatId": 11,
    "name": "Oqqo‘rg‘on tumani",
    "nameUz": "Оққўрғон тумани"
  },
  {
    "id": 159,
    "viloyatId": 11,
    "name": "Olmaliq shahri",
    "nameUz": "Олмалиқ шаҳри"
  },
  {
    "id": 160,
    "viloyatId": 11,
    "name": "Ohangaron tumani",
    "nameUz": "Оҳангарон тумани"
  },
  {
    "id": 161,
    "viloyatId": 11,
    "name": "Parkent tumani",
    "nameUz": "Паркент тумани"
  },
  {
    "id": 162,
    "viloyatId": 11,
    "name": "Piskent tumani",
    "nameUz": "Пискент тумани"
  },
  {
    "id": 163,
    "viloyatId": 11,
    "name": "O‘rta Chirchiq tumani",
    "nameUz": "Ўрта Чирчиқ тумани"
  },
  {
    "id": 164,
    "viloyatId": 11,
    "name": "Chinoz tumani",
    "nameUz": "Чиноз тумани"
  },
  {
    "id": 165,
    "viloyatId": 11,
    "name": "Chirchiq shahri",
    "nameUz": "Чирчиқ шаҳри"
  },
  {
    "id": 166,
    "viloyatId": 11,
    "name": "Yuqori Chirchiq tumani",
    "nameUz": "Юқори Чирчиқ тумани"
  },
  {
    "id": 167,
    "viloyatId": 11,
    "name": "Yangiyo‘l tumani",
    "nameUz": "Янгийўл тумани"
  },
  {
    "id": 168,
    "viloyatId": 12,
    "name": "Beshariq tumani",
    "nameUz": "Бешариқ тумани"
  },
  {
    "id": 169,
    "viloyatId": 12,
    "name": "Bag‘dod tumani",
    "nameUz": "Бағдод тумани"
  },
  {
    "id": 170,
    "viloyatId": 12,
    "name": "Buvayda tumani",
    "nameUz": "Бувайда тумани"
  },
  {
    "id": 171,
    "viloyatId": 12,
    "name": "Dang‘ara tumani",
    "nameUz": "Данғара тумани"
  },
  {
    "id": 172,
    "viloyatId": 12,
    "name": "Yozyovon tumani",
    "nameUz": "Ёзёвон тумани"
  },
  {
    "id": 173,
    "viloyatId": 12,
    "name": "Quva tumani",
    "nameUz": "Қува тумани"
  },
  {
    "id": 174,
    "viloyatId": 12,
    "name": "Quvasoy shahri",
    "nameUz": "Қувасой шаҳри"
  },
  {
    "id": 175,
    "viloyatId": 12,
    "name": "Qo‘qon shahri",
    "nameUz": "Қўқон шаҳри"
  },
  {
    "id": 176,
    "viloyatId": 12,
    "name": "Qo‘shtepa tumani",
    "nameUz": "Қўштепа тумани"
  },
  {
    "id": 177,
    "viloyatId": 12,
    "name": "Marg‘ilon shahri",
    "nameUz": "Марғилон шаҳри"
  },
  {
    "id": 178,
    "viloyatId": 12,
    "name": "Oltiariq tumani",
    "nameUz": "Олтиариқ тумани"
  },
  {
    "id": 179,
    "viloyatId": 12,
    "name": "Rishton tumani",
    "nameUz": "Риштон тумани"
  },
  {
    "id": 180,
    "viloyatId": 12,
    "name": "So‘x tumani",
    "nameUz": "Сўх тумани"
  },
  {
    "id": 181,
    "viloyatId": 12,
    "name": "Toshloq tumani",
    "nameUz": "Тошлоқ тумани"
  },
  {
    "id": 182,
    "viloyatId": 12,
    "name": "Uchko‘prik tumani",
    "nameUz": "Учкўприк тумани"
  },
  {
    "id": 183,
    "viloyatId": 12,
    "name": "O‘zbekiston tumani",
    "nameUz": "Ўзбекистон тумани"
  },
  {
    "id": 184,
    "viloyatId": 12,
    "name": "Farg‘ona tumani",
    "nameUz": "Фарғона тумани"
  },
  {
    "id": 185,
    "viloyatId": 12,
    "name": "Farg‘ona shahri",
    "nameUz": "Фарғона шаҳри"
  },
  {
    "id": 186,
    "viloyatId": 12,
    "name": "Furqat tumani",
    "nameUz": "Фурқат тумани"
  },
  {
    "id": 187,
    "viloyatId": 13,
    "name": "Bog‘ot tumani",
    "nameUz": "Боғот тумани"
  },
  {
    "id": 188,
    "viloyatId": 13,
    "name": "Gurlan tumani",
    "nameUz": "Гурлан тумани"
  },
  {
    "id": 189,
    "viloyatId": 13,
    "name": "Qo‘shko‘pir tumani",
    "nameUz": "Қўшкўпир тумани"
  },
  {
    "id": 190,
    "viloyatId": 13,
    "name": "Urganch tumani",
    "nameUz": "Урганч тумани"
  },
  {
    "id": 191,
    "viloyatId": 13,
    "name": "Urganch shahri",
    "nameUz": "Урганч шаҳри"
  },
  {
    "id": 192,
    "viloyatId": 13,
    "name": "Xiva tumani",
    "nameUz": "Хива тумани"
  },
  {
    "id": 193,
    "viloyatId": 13,
    "name": "Hazorasp tumani",
    "nameUz": "Ҳазорасп тумани"
  },
  {
    "id": 194,
    "viloyatId": 13,
    "name": "Xonqa tumani",
    "nameUz": "Хонқа тумани"
  },
  {
    "id": 195,
    "viloyatId": 13,
    "name": "Shovot tumani",
    "nameUz": "Шовот тумани"
  },
  {
    "id": 196,
    "viloyatId": 13,
    "name": "Yangiariq tumani",
    "nameUz": "Янгиариқ тумани"
  },
  {
    "id": 197,
    "viloyatId": 13,
    "name": "Yangibozor tumani",
    "nameUz": "Янгибозор тумани"
  },
  {
    "id": 198,
    "viloyatId": 14,
    "name": "Bektemir tumani",
    "nameUz": "Бектемир тумани"
  },
  {
    "id": 199,
    "viloyatId": 14,
    "name": "Mirzo Ulug‘bek tumani",
    "nameUz": "Мирзо Улуғбек тумани"
  },
  {
    "id": 200,
    "viloyatId": 14,
    "name": "Mirobod tumani",
    "nameUz": "Миробод тумани"
  },
  {
    "id": 201,
    "viloyatId": 14,
    "name": "Olmazor tumani",
    "nameUz": "Олмазор тумани"
  },
  {
    "id": 202,
    "viloyatId": 14,
    "name": "Sergeli tumani",
    "nameUz": "Сергели тумани"
  },
  {
    "id": 203,
    "viloyatId": 14,
    "name": "Uchtepa tumani",
    "nameUz": "Учтепа тумани"
  },
  {
    "id": 204,
    "viloyatId": 14,
    "name": "Yashnobod tumani",
    "nameUz": "Яшнобод тумани"
  },
  {
    "id": 205,
    "viloyatId": 14,
    "name": "Chilonzor tumani",
    "nameUz": "Чилонзор тумани"
  },
  {
    "id": 206,
    "viloyatId": 14,
    "name": "Shayxontohur tumani",
    "nameUz": "Шайхонтоҳур тумани"
  },
  {
    "id": 207,
    "viloyatId": 14,
    "name": "Yunusobod tumani",
    "nameUz": "Юнусобод тумани"
  },
  {
    "id": 208,
    "viloyatId": 14,
    "name": "Yakkasaroy tumani",
    "nameUz": "Яккасарой тумани"
  },
  {
    "id": 209,
    "viloyatId": 1,
    "name": "Taxiatosh shahri",
    "nameUz": "Тахиатош шаҳри"
  },
  {
    "id": 210,
    "viloyatId": 2,
    "name": "Asaka shahri",
    "nameUz": "Асака шаҳри"
  },
  {
    "id": 211,
    "viloyatId": 9,
    "name": "Bandixon tumani",
    "nameUz": "Бандихон тумани"
  },
  {
    "id": 212,
    "viloyatId": 11,
    "name": "Ohangaron shahri",
    "nameUz": "Оҳангарон шаҳри"
  },
  {
    "id": 213,
    "viloyatId": 11,
    "name": "Yangiyo‘l shahri",
    "nameUz": "Янгийўл шаҳри"
  },
  {
    "id": 215,
    "viloyatId": 11,
    "name": "Toshkent tumani",
    "nameUz": "Тошкент тумани"
  },
  {
    "id": 216,
    "viloyatId": 1,
    "name": "Bo'zatov tumani",
    "nameUz": "Бўзатов тумани"
  },
  {
    "id": 217,
    "viloyatId": 13,
    "name": "Tuproqqal‘a tumani",
    "nameUz": "Тупроққалъа тумани"
  },
  {
    "id": 218,
    "viloyatId": 5,
    "name": "Ko'kdala tumani",
    "nameUz": "Кўкдала тумани"
  },
  {
    "id": 1001,
    "viloyatId": 2,
    "name": "Bo‘ston tumani",
    "nameUz": "Бўстон тумани"
  },
  {
    "id": 1002,
    "viloyatId": 2,
    "name": "Xo‘jaobod tumani",
    "nameUz": "Хўжаобод тумани"
  },
  {
    "id": 1003,
    "viloyatId": 14,
    "name": "Yangihayot tumani",
    "nameUz": "Янгиҳаёт тумани"
  }
] as const;
